namespace MvcCore.TagHelpers
{
    public enum InputControlType
    {
        Button,
        Checkbox,
        Color,
        Date,
        DateTime,
        DateTimeLocal,
        Month,
        Week,
        Time,
        Email,
        File,
        Hidden,
        Image,
        Number,
        Password,
        Radio,
        Range,
        Reset,
        Search,
        Submit,
        Tel,
        Text,
        Url
    }
}
